#!/bin/bash
set -o nounset -o errexit -o pipefail

IP_ADDR=$(/sbin/ifconfig eth0 | grep "inet addr" | cut -d ":" -f2 | cut -d " " -f1)

## Set Jupyter notebook configs
CONF_FILE="${HOME}/.jupyter/jupyter_notebook_config.py"

touch "${CONF_FILE}"

cat <<EOF >>"${CONF_FILE}"
c.NotebookApp.notebook_dir = '${DRT_WORKING_DIR:-"/"}'
c.NotebookApp.tornado_settings = {'headers': {'Content-Security-Policy': 'frame-ancestors *'}}
c.NotebookApp.default_url = '/tree${DOMINO_WORKING_DIR}'
c.NotebookApp.token = ''
EOF

## Get Spark Master Node public/private DNS/IP and update /home/ubuntu/.sparkmagic/config.json
LIVY_SERVERNAME=${DRT_LIVY_SERVER_HOSTNAME}
LIVY_USERNAME=${DRT_LIVY_SERVER_USERNAME}
LIVY_PASSWORD=${DRT_LIVY_SERVER_PASSWORD}
LIVY_AUTH_TYPE=${DRT_LIVY_SERVER_AUTH_TYPE}

sed -i "s/localhost/${LIVY_SERVERNAME}/g" /home/ubuntu/.sparkmagic/config.json
sed -i "s/livyusername/${LIVY_USERNAME}/g" /home/ubuntu/.sparkmagic/config.json
sed -i "s/livypassword/${LIVY_PASSWORD}/g" /home/ubuntu/.sparkmagic/config.json
sed -i "s/livyauth/${LIVY_AUTH_TYPE}/g" /home/ubuntu/.sparkmagic/config.json

echo "Livy server is set to: ${LIVY_SERVERNAME}"

# Replace * in "--ip=*" with the actual IP address of the container
COMMAND='jupyter notebook --no-browser --ip=* 2>&1'
FINAL_COMMAND=$(echo "${COMMAND}" | sed "s/--ip=\\*/--ip=${IP_ADDR}/")

eval ${FINAL_COMMAND}
